### PR TITLE
Merge from master (removes selectors backport)

### PR DESCRIPTION
**Pull request by pquentin**

### CODE REVIEW

**Comment by pquentin** [comment]
😀 Right, the merge was the difficult part, but it was not that hard! `-X patience` and diff3 conflict style helped a lot. The main issues were:

 * v2 has [less chunked tests](https://github.com/python-trio/urllib3/commit/51d0efeb72413914d98f5efc267ad650d91ff5df), but git re-added some of them without asking
 * the _async files where by default git can't help, maybe there's a trick to help with that?
 * [isclosed in response.py](https://github.com/python-trio/urllib3/pull/39/files#diff-f118712ca576f053d25bc4f0a6fe905aR196) where I'm not fully confident that I made the correct change. https://github.com/python-trio/urllib3/pull/39/commits/bdacb3f975a4ec460904477f5c6ce050bebf44dd and https://github.com/python-trio/urllib3/pull/39/commits/368717c6b2ccf908170808aaf5891be28e80f0da are the relevant commits, but the tests no longer exists in our branch (sorry, I should have mentioned that issue before)

I can't be fully confident that I did not make any mistakes but I figured out that the tests still pass, so it can't be too wrong? I guess I could also do the merge again now that I understand the commits from master better.

----

Regarding the return values of the wait call, I agree that we can worry about it later and that test_sync_connection.py should be about the sync backend. Also, even if we decided to put the timeout and is_readable tests in this file, those tests won't require extracting the readable/writable status from the general wait_for_socket call, so it will be easy to add?

**Comment by pquentin** [comment]
Having slept on it, I do plan to make the merge again, but not sure when.

**Comment by njsmith** [comment]
I think the `isclosed` stuff is all going to have to be revisited when we get around to refactoring that properly – right now `Response` inherits from [`IOBase`](https://docs.python.org/3/library/io.html#io.IOBase), and wraps a file object, .... but the async version just... can't do that, the interfaces are different. So I wouldn't worry about it too much right now either way.

> the _async files where by default git can't help, maybe there's a trick to help with that?

IIRC I ended up doing silly things like `git diff $(git merge-base master bleach-spike) bleach-spike <path>` to see the changes, and then running it through `patch` with some carefully chosen `-p1` option to point it at the right file. I guess that can be a trick?

Alternatively... maybe we should give #29 a try and see if it helps?

> Having slept on it, I do plan to make the merge again, but not sure when.

Honestly if you want to merge this, I'd be fine with it; we can't get hung up worrying about perfection, and the tests are passing, so it's probably fine. But if you'd rather do it again then that's fine too :-). Do you want to close this one then, or...?

**Comment by pquentin** [comment]
Thanks, that helps!

I'll try to work on the new merge this week.

**Comment by pquentin** [comment]
Merged! I performed the merge again, and am now more confident that it is correct.

**Pull request merged**
