### PR TITLE
Moved most of the metadata from setup.py to setup.cfg

### PR DESCRIPTION
**Pull request by agronholm**

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks! Can you please run black on setup.py?

**Comment by pquentin** [comment]
Thank you!

**Comment by agronholm** [comment]
It would've been nice to get `version` in setup.cfg as well, but the appropriate incantation (`version = attr: urllib3.__version__` fails because it implicitly imports not only dependencies, but generated code as well. This could be fixed by moving the version to a separate file, or (my preferred option) migrating the project to use setuptools_scm or similar, but that may be too much of a change for upstream.

**Comment by pquentin** [comment]
I have to admit a bias towards _version.py just like all other python-trio package do it, because having the same procedure everywhere helps when making releases (and possibly automating releases at some point).

However, upstream is not a concern, we're about to diverge more radically anyways.

**Comment by agronholm** [comment]
Having to remember to add a git tag as well as changing a Python file violates DRY, for no good reason IMO. Besides, there are other benefits like not having to bother with `MANIFEST.in`, and having a dev version automatically generated based on the VCS status.

**Comment by pquentin** [comment]
Okay that's quite compelling. :) And it looks like it won't interfere with our own setuptools magic, since if affects a different area.

**Comment by agronholm** [comment]
There is one downside though: providing a `__version__` attribute (if that is desired) gets a bit complicated because it will require either pkg_resources or `importlib.metadata` (only included in the stdlib from Python 3.8 onwards) and even then it will fail if the application has been packaged with tools like pyinstaller (which don't include the distribution metadata).

**Comment by pquentin** [comment]
Yeah, I think `__version__` is desired. It's easy to require a recent enough setuptools using pyproject.toml, so I think we can get pkg_resources easily? Regarding pyinstaller, does that mean it affects all users of the library that want to package their application using pyinstaller?

**Comment by agronholm** [comment]
> It's easy to require a recent enough setuptools using pyproject.toml, so I think we can get pkg_resources easily?

What I mean is that this will require adding either setuptools or importlib-metadata as a run-time dependency just to get the version number.

> Regarding pyinstaller, does that mean it affects all users of the library that want to package their application using pyinstaller?

Indeed – if we want to have a `__version__` field, it will have to be dug up programmatically at run time. And the source for that information is the `.dist-info` directory created during install, which does not exists anywhere in a pyinstaller created application.

**Comment by pquentin** [comment]
OK, I see. Significant downsides :(

**Comment by agronholm** [comment]
It's only if you want to keep the `__version__` attribute there. My projects don't have that so I don't have that problem.

**Comment by pquentin** [comment]
@agronholm I just realized that we need to keep the `__version__` attribute in order to send it as part of the user agent in the future

**Comment by sethmlarson** [comment]
What do we think about moving to flit since we can't have extensions anyways and then we can get away from setuptools entirely. :)

**Comment by njsmith** [comment]
I'm all for flit, except that it might not have a way to let us run our code generation step.

**Comment by pquentin** [comment]
Yeah, we're overriding build_py from setuptools to generate the sync code from the async code using https://github.com/python-trio/unasync/, I don't how that would work with flit. I guess it would have to become a separate step in both nox and in the release-step process, so maybe that's too cumbersome.

**Comment by sethmlarson** [comment]
Yep you're both right, I'm still too new to the project :)

**Comment by pquentin** [comment]
@sethmlarson Keep your suggestions coming though, we need new perspectives! I learned today that flit was a nice replacement to setuptools (and works for Python 2 packages too), too bad our current setup does not allow it.

**Comment by pquentin** [comment]
@agronholm It turns out that setuptools_scm can write the version file itself, eg. with:

```
# pyproject.toml
[tools.setuptools_scm]
write_to = hip/_version.py
```

This is the configuration pytest uses, and it seems to work well for them.

**Comment by agronholm** [comment]
Yup, I was reminded of that a little while ago and I plan to use this feature in the wheel project too.

**Pull request merged**
