### PR TITLE
Compute coverage only for the sync urllib3

### PR DESCRIPTION
**Pull request by pquentin**
It should be more encouraging. :)

(Also upgrade dev dependencies. The two first commits come from urllib3/master)

### CODE REVIEW

**Comment by pquentin** [comment]
For some reason codecov does not want to admit that coverage is around 85%. At least pytest-cov shows that correctly. In https://travis-ci.org/python-trio/urllib3/jobs/417104963, for example, we get:

```
----------- coverage: platform linux, python 3.5.6-final-0 -----------
Name                                        Stmts   Miss  Cover
------------------------------------------------------------------------------------------------
.../urllib3/__init__.py                       22      1    95%
.../urllib3/_backends/__init__.py              0      0   100%
.../urllib3/_backends/_common.py               4      1    75%
.../urllib3/_backends/_loader.py              31      2    94%
.../urllib3/_backends/sync_backend.py         78      3    96%
.../urllib3/_backends/trio_backend.py         44     44     0%
.../urllib3/_backends/twisted_backend.py     148    148     0%
.../urllib3/_collections.py                  148      0   100%
.../urllib3/_sync/__init__.py                  0      0   100%
.../urllib3/_sync/connection.py              189      8    96%
.../urllib3/_sync/connectionpool.py          230      2    99%
.../urllib3/_sync/poolmanager.py             153      0   100%
.../urllib3/_sync/request.py                  34      0   100%
.../urllib3/_sync/response.py                210      3    99%
.../urllib3/backends.py                        6      0   100%
.../urllib3/base.py                           23      1    96%
.../urllib3/connection.py                    130     92    29%
.../urllib3/connectionpool.py                  1      0   100%
.../urllib3/contrib/__init__.py                0      0   100%
.../urllib3/contrib/socks.py                  36      7    81%
.../urllib3/exceptions.py                     66      0   100%
.../urllib3/fields.py                         62      0   100%
.../urllib3/filepost.py                       32      0   100%
.../urllib3/poolmanager.py                     1      0   100%
.../urllib3/request.py                         1      1     0%
.../urllib3/response.py                        1      0   100%
.../urllib3/util/__init__.py                   1      0   100%
.../urllib3/util/connection.py                47      1    98%
.../urllib3/util/queue.py                     10      0   100%
.../urllib3/util/request.py                   37      0   100%
.../urllib3/util/response.py                  10      0   100%
.../urllib3/util/retry.py                    131      0   100%
.../urllib3/util/ssl_.py                      84      0   100%
.../urllib3/util/timeout.py                   48      0   100%
.../urllib3/util/url.py                       98      0   100%
.../urllib3/util/wait.py                      66     21    68%
------------------------------------------------------------------------------------------------
TOTAL                                       2182    335    85%
```

**Comment by njsmith** [comment]
How weird. And https://codecov.io/gh/python-trio/urllib3/tree/a2d22c6cbcb5baccd8a0409a46ddad1c5ae7ebab/src/urllib3 is missing a bunch of files, too...

**Comment by pquentin** [comment]
I think the missing files are the ones explicitly excluded in .coveragerc. It's surprising that urllib3/contrib/socks.py is missing, though.

**Comment by pquentin** [comment]
As mentioned by @njsmith in private chat, https://codecov.s3.amazonaws.com/v4/raw/2018-08-17/E2E8803D86D36097D9590B249A83A944/a2d22c6cbcb5baccd8a0409a46ddad1c5ae7ebab/eab02779-20cb-4f7d-b741-f7f0ec9be99c.txt shows that `coverage xml` output is incorrect, so that will help me reproduce the problem and fix it

**Comment by pquentin** [comment]
It turns out that to get correct codecov coverage, we need to use coverage.py directly to collapse the tox paths: see https://github.com/pyca/cryptography/pull/1468. But at that point, I don't know yet how to get coverage data on _sync files, since they're not in the source distribution. I'm closing this PR for now.

**Pull request closed without merging**
