### PR TITLE
move _sync codegen to tox.ini

### PR DESCRIPTION
**Pull request by oliland**
This appears to allow me to run the tests without messing around with virtualenv's a la the `runtests.py` script.

### CODE REVIEW

**Comment by njsmith** [comment]
I'm squinting at this and I guess it does what it says on the tin... But really the idea with tox support would be to take advantage of tox's workflow of "set up env, install urllib3 into the env via the usual installation mechanisms, then test the installed urllib3" instead of continuing to mutate the source directory in-place like we are now. BUT, there's this issue with pytest where if you have the source tree and tests in the same directory, then you end up being forced to only test the source tree, never the installed version: https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules

Hence: #29 

(If you don't want to start digging down this rabbithole, then I'd also accept a PR to change runtests.py to use `venv` instead of `virtualenv`. :-))

**Comment by njsmith** [comment]
I should also say: if this is, like, what you need to do temporarily to unblock yourself, then we can merge it and fix it up later once we have the tests in better shape etc. The message above is more context to make that call :-)

**Comment by oliland** [comment]
Agree that #29 is the right approach - happy to leave this unmerged and just use it on my fork.

I encountered further problems when using `runtests.py` beyond just swapping `virtualenv` with `venv`. They didn't seem like getting into given that it's just a temporary script, so I'm just sharing this as it allowed me to run the tests.

**Comment by njsmith** [comment]
> happy to leave this unmerged and just use it on my fork.

I've carried around unmerged local changes in my working copy before, and it's exhausting always remembering not to commit them... how about adding some comments around this like `# XX temporary hack until  https://github.com/python-trio/urllib3/issues/29 is fixed` and then we can merge it?

(And [then you'll have permissions](https://trio.readthedocs.io/en/latest/contributing.html#joining-the-team) to request reviews and stuff :-).)

**Comment by oliland** [comment]
@njsmith Thanks - Indeed I think that would help me out. I've added the comment you suggested.

**Comment by pquentin** [comment]
@oliland Thank you for your contribution! 🎉

**Comment by njsmith** [comment]
And [invitation sent!](https://trio.readthedocs.io/en/latest/contributing.html#joining-the-team)

**Pull request merged**
