### PR TITLE
Attempt to fix subtle logic bug in sync backend flow control

### PR DESCRIPTION
**Pull request by njsmith**
I'm not sure if this actually fixes the issue @pquentin diagnosed in #24 -- in fact I haven't even tried testing it yet, so let's see what the CI says :-). But I think it does fix a real logic bug...

### CODE REVIEW

**Comment by njsmith** [comment]
Wow, this isn't working at all. AFAIK those two commits should both have fixed bugs, but the failure count went up after each one :-). I may need to come back to this tomorrow...

**Comment by pquentin** [comment]
The changes look good to me. Changing such a core part of urllib3 will break tests! I can investigate next week if you want.

**Comment by njsmith** [comment]
> I use builds on branches to test my changes. Maybe we can exclude branches with a given prefix (Travis accepts regexes) or move the repo to the python-trio org?

Oh, okay! I'll drop that commit from here, and yeah, one of those could work. Or even the requests/ org, if the urllib3 maintainers continue to be too busy to review our proposal...

> The changes look good to me. Changing such a core part of urllib3 will break tests! I can investigate next week if you want.

Hopefully I'll get to it before then, but if not then that'd be great :-).

After sleeping on it, I wonder if the failures are just, these tests were always broken but because we were swallowing exceptions they looked like they passed... I know we don't yet have a proper design for converting the different backends' low-level exceptions into the exceptions that urllib3 should be raising publicly.

**Comment by pquentin** [comment]
Turns out I found time to look at this today!

* The test_sync_connection tests were genuinely failing. I fixed them in the https://github.com/pquentin/urllib3/tree/sync-duplex-blocking-bug-pquentin branch, but I don't know if https://github.com/pquentin/urllib3/commit/d4aa1e411f61da2f45e31dd9278f105b2ad2bef2 is correct. (In the future, I'll simplify those tests because we don't look at the return value from the `_wait` call, but that's unrelated to the issue at hand.)
 * The other tests were indeed broken: they don't contain assertions, but only fail if an exception is thrown. They're all related to https. I tried to mark them with xfail annotations, but it looks like the failures are not fully deterministic. I can mark them as `xfail(strict=False)` instead, but getting to deterministic failures would be better if it's not too hard.

One issue to fix is that recv in and send in urllib3/contrib/pyopenssl.py handle the WantRead/WantWrite cases themselves, so we will probably need to stop that, and switch from the ssl exceptions to the pyOpenSSL ones.

Hope that helps!

**Comment by njsmith** [comment]
I'm confused about that patch you linked. My understanding is that `send`
should never return 0; either it should return a positive integer or else
it should raise an exception. Is this something that's actually happening,
or is it something a test is generating with a mocked `send`?

Re: pyopenssl: I guess we'll need to move all that code into the sync
backend...

**Comment by pquentin** [comment]
It only happens with a mocked `send`. I incorrectly assumed that if it was mocked, then it could happen. I'll be happy to remove that part.

And yes, we'll need to move all that code in the sync backend. Will the other backends be affected? If you want to tackle that, I'd be happy to fill the holes and look at the tests.

**Comment by pquentin** [comment]
See https://github.com/pquentin/urllib3/tree/sync-duplex-blocking-bug-pquentin-2 for the updates test_sync_connection fixes.

**Comment by njsmith** [comment]
Okay, I dropped that change to .travis.yml (now that we've moved the repo), and pulled your sync-duplex-blocking-bug-pquentin-2 branch, now let's see what travis and appveyor say :-)

> And yes, we'll need to move all that code in the sync backend. Will the other backends be affected?

I think the pyopenssl code is mostly needed to work around issues with the stdlib `ssl` module on old python 2.7 releases (in particular, it didn't use to do hostname validation at all!). And Trio and Twisted both provide their own ssl support that we piggy-back off of and don't want to replace, because it's not at all simple. (Internally, Trio always uses the stdlib `ssl` module, which I think is fine on all the versions of Python that trio supports. Internally, Twisted always uses pyopenssl.)

**Comment by njsmith** [comment]
So anyway what I'm saying is, I think it makes sense to only worry about pyopenssl in the sync backend.

**Comment by njsmith** [comment]
Now where did appveyor go...

**Comment by njsmith** [comment]
@pquentin Also travis is saying `23 failed, 685 passed, 210 skipped, 37 xfailed, 78 warnings in 79.58 seconds` – is that what you'd expect for the branch, or has something gone weird?

**Comment by njsmith** [comment]
Okay, got appveyor working again at least.

**Comment by pquentin** [comment]
I can't check right now but those numbers are what I would expect, yes!

**Comment by pquentin** [comment]
> So anyway what I'm saying is, I think it makes sense to only worry about pyopenssl in the sync backend.

Thanks, I finally had figured that much but your explanations are much better than what I had in mind! 

Things to do before merging:

 * Mark the 23 xfailed test, or skip them if they're not deterministic
 * Remove the .travis.yml change

Not sure when I'll be able to do that yet!

**Comment by njsmith** [comment]
Ok, the tests are passing here locally, and I removed the .travis.yml change, so if the CI passes then I think this is ready to merge.

**Comment by njsmith** [comment]
Oh whoa what the heck, I swear I rebased it away :-) thanks for nagging...

**Comment by pquentin** [comment]
Thank you!

**Pull request merged**
