### PR TITLE
Trying to make a test pass for trio

### PR DESCRIPTION
**Pull request by RatanShreshtha**
I have install pytest-trio and setup the pytest.ini file but still I keep getting 
```
test/with_dummyserver/test_async_poolmanager.py::TestPoolManager::test_redirect
  /usr/lib64/python3.7/unittest/case.py:632: RuntimeWarning: coroutine 'TestPoolManager.test_redirect' was never awaited
    testMethod()

```

Am I on right track ?

### CODE REVIEW

**Comment by njsmith** [comment]
One possibility is that pytest-trio doesn't play nicely with pytest's backwards compatibility handling for unittest-based tests.

**Comment by pquentin** [comment]
@njsmith I can confirm that this is the issue: when removing the parent class `HTTPDummyServerTestCase`, the test runs (but fails). So it would be nice to remove unittest from urllib3 tests but it's likely to be a lot of work (and it needs to be done upstream).

**Comment by njsmith** [comment]
It might be as simple as:

* Deleting the `unittest.TestCase` base class everywhere
* Replacing all `def setUp` with `def setup_method` ([ref](https://docs.pytest.org/en/latest/xunit_setup.html#method-and-function-level-setup-teardown))
* Delete all other references to `unittest` (imports, `if __name__ == "__main__": unittest.main()`)

**Comment by pquentin** [comment]
@njsmith Great idea, thanks! I did just that. I also had to:

 * change the assertEqual calls
 * declare `*TestCase` classes as test classes
 * call super().setup_class() manually (this is why most sync tests are now broken: they don't do this)
 * remove the call to self.addCleanup() (the context manager is enough, and pytest does not support addCleanup)

And add a bunch of forgotten async/await statements in the main code. :)

The result is here: https://github.com/pquentin/urllib3/commits/WIP_trio_tests

The test passes on Python 3.6+, but I still have a warning because the HTTPResponse.data property calls read(), which is an async function. But luckily we don't read the body here, so I did not have to fix it to get the test to pass.

I think the next step for this experiment is to asyncify the tests and run unasync on them.

**Comment by RatanShreshtha** [comment]
Should I try to remove unittest from one test case class and also change corresponding tests and see if they pass for sync ?
And then try to work on asyncify the tests and run unasync on them.

**Comment by RatanShreshtha** [comment]
I am not sure how to asyncify the tests, I have few doubts like how we are going to differentiate between things like `PoolManager` vs. `AsyncPoolManager` or different paths `urllib3._sync.connectionpool` vs `urllib3._async.connectionpool`.

One way suggested by @pquentin is to use pytest fixture for abstracting the difference.
And how can we run unasync on tests ?

**Comment by pquentin** [comment]
@RatanShreshtha I personally don't really know what to do next, I need to try a few things before, but I'm currently focused on merging the changes from master. Sorry about that! There's always #94 which is a well-defined issue to work on.

**Comment by pquentin** [comment]
Oh, you deleted the branch. I'm keeping https://github.com/pquentin/urllib3/commits/WIP_trio_tests until we added its contents

**Comment by pquentin** [comment]
Okay, urllib3 master now uses pure pytest: https://github.com/urllib3/urllib3/pull/1649 Now there are six months of commits to catch up...

**Comment by pquentin** [comment]
> Now there are six months of commits to catch up...

Done!

Let's continue the discussion in #122.

**Pull request closed without merging**
