### PR TITLE
Report coverage for sync code only

### PR DESCRIPTION
**Pull request by pquentin**
We'll reach 100% when we'll have feature parity with the master branch. Then we'll worry about testing async support.

I'm not sure yet how codecov will like this, because coverage now outputs the full paths starting with ".tox/...". Let's find out!

### CODE REVIEW

**Comment by pquentin** [comment]
All jobs report >90% coverage, and codecov received the reports correctly ([example](https://codecov.io/codecov/v4/raw/2018-12-07/E2E8803D86D36097D9590B249A83A944/2fc80c95e111b7f63350b7bc0e67eaf39f57b5a1/fe43eec3-3ad3-4af5-8b4b-75a0783321fc.txt)). I don't know why the correct files don't show up there, but I hope it will get fixed eventually as codecov realize what are the new covered files? I don't think the ".tox/py35/lib/python3.5/site-packages/urllib3/connection.py" are the problem.

**Comment by pquentin** [comment]
I think I understand why codecov behaves this way. codecov looks at the source code in git, and only considers files that are both in the coverage report and in GitHub.

Ah, this is confirmed in the docs. https://docs.codecov.io/docs/fixing-paths says:

> For Codecov to operate properly, all files must match the git/hg file structure. Codecov has internal methods of mapping paths, but they may not work properly on all projects. You may provide patterns to fix file paths manually, to map them back accordingly.

This is why the [coverage report](https://codecov.io/gh/python-trio/urllib3/pull/62/tree/src/urllib3) does not show the _async dir (it's not in coverage reports), and this why it does not show the _sync dir (it's not in the source).

I need to figure out how the fixing path feature works, and map from _sync back to _async. But that won't work when we'll want coverage for _async too.

I could also stop using codecov, and write a custom script that grabs the coverage reports somewhere and ouputs a combined coverage report without looking at the code.

**Comment by njsmith** [comment]
Oh, that's nasty. And seems pretty intrinsic: https://docs.codecov.io/docs/caveats

Codecov does have a feature to let you "tag" coverage reports, so you can e.g. check what coverage you got on just Windows, or just on py2, etc.: https://docs.codecov.io/docs/flags

I wonder if it would be viable to map the `_sync` paths to the `_async` paths, but with a different tag, so you can toggle it on and off in the viewer?

This would probably require doing some hacking of the coverage information to split the coverage data for the `_sync` and `_async` directories into separate files, that could be uploaded separately. But at least that's just some local data structure hacking on some files that we control, rather than convincing a third party service to fundamentally change their architecture...

**Comment by njsmith** [comment]
For now, just mapping `_sync` to `_async` and merging them together seems like a good approach... we don't need to solve everything to get something useful :-)

**Comment by pquentin** [comment]
@njsmith Oh, that's a clever idea! Thanks.

For now, as you said, I'd like to be able to map _sync to _async, and well, it does not seem to work. :) I'll continue working on it, and will request a review again when I'm done.

**Comment by pquentin** [comment]
For some reason Travis did not pick up the latest commit. Cycling.

**Comment by pquentin** [comment]
codecov is now convinced about the 93% coverage. 🎉

Please take a look.

**Comment by njsmith** [comment]
Oof. Well, the PR is a mess, but it all seems to be because the problems you're dealing with are horribly messy :-). Let's get this merged and if something comes back to bite us later then we can deal with it then... and hopefully you can take a break from fighting with CI for at least a little while!

**Pull request merged**
