### PR TITLE
Added the AnyIO backend

### PR DESCRIPTION
**Pull request by agronholm**

### CODE REVIEW

**Comment by pquentin** [comment]
Thank you @agronholm! Awesome contribution. Can you specify the type annotations as comments to make sure Python 2.7 can parse anyio_backend.py? We may want to drop Python 2.7, but I would like to make sure it's a deliberate decision.

**Comment by agronholm** [comment]
1. Why is it necessary for Python 2 to parse the module?
1. The `async def` makes that already impossible, doesn't it?

**Comment by pquentin** [comment]
Hmmm, yeah, good catch, I need to understand how we're doing this for the trio backend. I also don't understand why codecov is seeing anyio_backend.py but not the twisted backend. Will investigate.

**Comment by pquentin** [comment]
Okay found the issue. You need to add `*urllib3/_backends/anyio_backend.py` to .coveragerc. I guess we should move the coverage configuration to setup.cfg too, to make it more discoverable. (This is where I looked first.)

**Comment by agronholm** [comment]
I'll do that and afterwards make another PR for that change.

**Comment by pquentin** [comment]
Thanks! Feel free to merge when the tests pass. :)

**Comment by agronholm** [comment]
Is it normal for the docs tests to fail or should I change something?

**Comment by pquentin** [comment]
However the codecov/patch failure means we should test loading the anyio backend in test_backends.py

**Comment by pquentin** [comment]
codecov is now happy with this PR: https://codecov.io/gh/python-trio/urllib3/pull/140/tree

But for some reason did not update the check on GitHub. (This is why it's not required.)

Thanks, merging!

**Comment by pquentin** [comment]
Damn, I hit on close instead. Now we have to wait for all the tests again...

**Comment by agronholm** [comment]
> Yes, the docs tests are expected to fail, as you can see Travis is happy with it.

Travis is not happy about it and since Travis tests are required to pass, merging is blocked.

**Comment by pquentin** [comment]
> Travis is not happy about it and since Travis tests are required to pass, merging is blocked.

No, a Python 3.6 build was failing (I think it was due to https://github.com/urllib3/urllib3/pull/1751), so I restarted it and then Travis became happy.

Anyway, thank you for your contribution! Merged! We now have an anyio backend :tada:

**Pull request merged**
