### PR TITLE
Reset h11 state machines on socket close

### PR DESCRIPTION
**Pull request by pquentin**
The idea is to always match the socket state.

Closes https://github.com/python-trio/urllib3/issues/71

### CODE REVIEW

**Comment by njsmith** [comment]
It's counterintuitive that having an idle h11 connection is somehow supposed to represent having no socket connection at all. Naively I'd expect something like `self._state_machine = None`... at the least it seems like it needs a comment explaining what's going on :-)

**Comment by pquentin** [comment]
You're right, I need to fix that.

**Comment by pquentin** [comment]
@njsmith I tried to do just that, please take a look!

(Travis Linux builds are currently slow to boot: https://www.traviscistatus.com/incidents/my5wm56npf7q so I don't expect CI to finish soon.)

**Comment by pquentin** [comment]
The `TestSocketClosing.test_connection_cleanup_on_read_timeout` failure is also present on the master branch, see https://github.com/urllib3/urllib3/pull/1554#issuecomment-474330880.

**Comment by pquentin** [comment]
Trying again anyway.

**Comment by njsmith** [comment]
Is the idea that `self._state_machine` should be None if, and only if, `self._sock` is None? If so then:

- In `connect` you should wait for `self._sock` to be successfully assigned before assigning `self._state_machine`

- In `close` you should set `self._state_machine = None`

**Comment by pquentin** [comment]
Thanks, trying this now. That makes more sense!

I think my latest modification to the `complete` property is now correct, but I'm not sure if this is the best way to do it. I don't understand why the tests seemed to pass when I was returning False though.

**Comment by pquentin** [comment]
@RatanShreshtha Thanks, done. Is that OK with you?

I also removed the tox pin because the new version works.

@njsmith Can you please take another look? Thanks!

**Pull request merged**
