### PR TITLE
Removed support for Python 3.4

### PR DESCRIPTION
**Pull request by agronholm**

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks! Can you please modify `test/__init__.py` and `_travis/isntall.sh` too? As done in https://github.com/python-trio/urllib3/pull/145/files

**Comment by agronholm** [comment]
The URL points to this PR, but I've removed mentions of 3.4 I could find from those files.

**Comment by pquentin** [comment]
Sorry I meant https://github.com/urllib3/urllib3/pull/1686, but yes those were the changes to make.

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
