### PR TITLE
Merge from master (July 26th, 2019)

### PR DESCRIPTION
**Pull request by pquentin**
There are two main changes in this pull request: it switches to pure pytest (finally!) and removes the rfc3986 dependency. Sorry, @RatanShreshtha, I had this code ready before you submitted #120, but wanted to sleep on it before submitting it. So, unfortunately, this closes #120. Thank you for your work, and sorry about that.

I did not include the gcp-devrel change because we don't support Python 3.4 anyways, and it will be dropped soon in the master branch (as soon as we fix the CI there).

After this PR, there will only be three commits left in the master branch to merge. And only one of them is difficult: https://github.com/urllib3/urllib3/pull/1652. We probably want to make auto close the default, but this code changed a lot in the async version, and I need to understand it again before taking a decision here.

But the nice thing here is that we'll finally be able to use pytest-trio. :tada:

(Oh, I use three times `git merge`, so it's probably better to review those merge commits one by one instead of looking at everything at once.)

### CODE REVIEW

**Comment by pquentin** [comment]
(Oops, I meant talking about #120, not #119. Fixed my comment above.)

**Comment by RatanShreshtha** [comment]
okay I am going to close #120

**Comment by pquentin** [comment]
Thank you @RatanShreshtha, sorry about that, we'll better coordinate next time.

I had a typo in upload_coverage.sh (pythom instead of python), I force pushed a commit to fix this.

**Comment by pquentin** [comment]
Thank you for the review!

**Pull request merged**
