### PR TITLE
WIP: Fix test connection failure

### PR DESCRIPTION
**Pull request by RatanShreshtha**

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks! That's a great start.

One thing is off: you don't want to call `socks.create_connection` in the connection pool, but in SOCKSConnection. But I don't know how that interacts with the new connection backends. Maybe @njsmith has an idea. Or maybe we should drop SOCKS support for now!

**Comment by njsmith** [comment]
There's a more basic problem here, which is that the SOCKS library is synchronous and does its own socket handling. We don't really have any way to fit this into our backend system. So even if we can get some of these tests to pass, I think we'll need to rethink this whole module to get something that really works. Maybe we should throw out the existing urllib3.contrib.socks module and rewrite it based on [this sans-io SOCKS library](https://github.com/mike820324/socks5/)? Or maybe there's some way to kluge the existing library together with the sync backend, and simply not support SOCKS when running in async mode? It's going to be a tricky problem.

We probably have to solve it eventually, because SOCKS proxies do get used. But it's definitely less important than getting the core HTTP functionality working.

So my suggestion: let's mark all the socks tests as skipped for now, and open an issue on this repo so that we do remember to come back to it eventually.

**Comment by RatanShreshtha** [comment]
I am closing this PR and opening an issue for socks proxy support.

**Comment by RatanShreshtha** [comment]
Closing in favor of https://github.com/python-trio/urllib3/issues/77.

**Pull request closed without merging**
